include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  language:
    strict-raw-types: true

linter:
  rules:
    public_member_api_docs: false
    avoid_print: false
    lines_longer_than_80_chars: false
    avoid_redundant_argument_values: false
    use_build_context_synchronously: false
    prefer_const_constructors: false
    # 禁用风格相关的规则
    cascade_invocations: false
    omit_local_variable_types: false
    prefer_int_literals: false
    directives_ordering: false
    sort_constructors_first: false
    # 禁用过于严格的规则
    avoid_dynamic_calls: false
    inference_failure_on_function_invocation: false
    inference_failure_on_instance_creation: false
    inference_failure_on_function_return_type: false
    # 禁用不必要的警告
    unawaited_futures: false
    avoid_slow_async_io: false
    use_if_null_to_convert_nulls_to_bools: false
    flutter_style_todos: false
    unnecessary_raw_strings: false
    use_raw_strings: false
    unnecessary_brace_in_string_interps: false
    use_named_constants: false
    eol_at_end_of_file: false
    file_names: false
    no_default_cases: false
    avoid_positional_boolean_parameters: false

