name: todolist
description: "Cross-platform personal productivity app."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.9.2
  flutter: '>=3.22.0'

dependencies:
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  fl_chart: ^0.69.0
  flex_color_scheme: ^8.3.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^3.1.1
  freezed_annotation: ^2.4.4
  go_router: ^16.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.5
  table_calendar: ^3.1.2
  timezone: ^0.10.1
  uuid: ^4.5.1
  just_audio: ^0.9.42
  audioplayers: ^6.1.0
  image_picker: ^1.1.2
  file_picker: ^8.1.6
  record: ^6.0.0
  signature: ^5.5.0
  speech_to_text: ^7.0.0  # 启用语音识别
  http: ^1.1.0
  google_mlkit_text_recognition: ^0.13.0  # OCR文字识别
  archive: ^3.4.0
  permission_handler: ^11.0.1
  connectivity_plus: ^6.0.0
  path: ^1.9.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  home_widget: ^0.7.0
  pdf: ^3.11.1
  # printing: ^5.13.4  # 暂时禁用，Windows构建需要nuget，待需要PDF打印时再启用
  open_file: ^3.5.9
  flutter_colorpicker: ^1.1.0
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  flutter_markdown: ^0.7.4+1
  markdown: ^7.2.2
  lunar: ^1.7.5
  share_plus: ^10.1.3
  confetti: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  riverpod_generator: ^2.3.5
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/dog_icon.png"
  adaptive_icon_background: "#FF9800"
  adaptive_icon_foreground: "assets/dog_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/dog_splash.png
  android: true
  ios: false





