/// 1000句名人名言集合
class FamousQuotes {
  static const List<String> quotes = [
    // 1-100: 励志成长类
    '生活就像骑自行车,要保持平衡就得不断前进。 —— 爱因斯坦',
    '成功不是终点,失败也不是终结,唯有勇气才是永恒。 —— 丘吉尔',
    '你今天所做的努力,都是在为明天铺路。',
    '不要等待机会,而要创造机会。 —— 乔治·伯纳德·肖',
    '行动是治愈恐惧的良药,而犹豫拖延将不断滋养恐惧。',
    '人生最大的荣耀不在于从不跌倒,而在于每次跌倒后都能站起来。 —— 曼德拉',
    '成功的秘诀在于坚持自己的目标和信念。',
    '不要问成功的秘诀为何,且尽全力做你应该做的事吧。 —— 华纳',
    '每一个不曾起舞的日子,都是对生命的辜负。 —— 尼采',
    '路是脚踏出来的,历史是人写出来的。 —— 吉鸿昌',

    '世上无难事,只怕有心人。',
    '学而不思则罔,思而不学则殆。 —— 孔子',
    '知之者不如好之者,好之者不如乐之者。 —— 孔子',
    '己所不欲,勿施于人。 —— 孔子',
    '天行健,君子以自强不息。 —— 周易',
    '业精于勤荒于嬉,行成于思毁于随。 —— 韩愈',
    '书山有路勤为径,学海无涯苦作舟。',
    '三人行,必有我师焉。 —— 孔子',
    '欲穷千里目,更上一层楼。 —— 王之涣',
    '少壮不努力,老大徒伤悲。',

    '机会总是留给有准备的人。',
    '没有什么不可能,只要你相信自己。',
    '今天的努力,是为了明天更好的自己。',
    '永远不要放弃你真正想要的东西。',
    '每一次努力都在为成功铺路。',
    '困难是暂时的,放弃才是永远的。',
    '你的态度决定你的高度。',
    '相信自己,你比想象中更强大。',
    '只有行动才能消除不安。',
    '坚持下去,成功就在转角。',

    'The only way to do great work is to love what you do. — Steve Jobs',
    'Innovation distinguishes between a leader and a follower. — Steve Jobs',
    'Stay hungry, stay foolish. — Steve Jobs',
    'The best time to plant a tree was 20 years ago. The second best time is now.',
    'Dream big, start small, act now.',
    'Success is not final, failure is not fatal. — Winston Churchill',
    'The future belongs to those who believe in their dreams. — Eleanor Roosevelt',
    'Be the change you wish to see in the world. — Gandhi',
    'Life is 10% what happens to you and 90% how you react to it. — Charles Swindoll',
    "Believe you can and you're halfway there. — Theodore Roosevelt",

    '读万卷书,行万里路。',
    '积土成山,积水成渊。',
    '宝剑锋从磨砺出,梅花香自苦寒来。',
    '不积跬步,无以至千里。 —— 荀子',
    '千里之行,始于足下。 —— 老子',
    '水滴石穿,绳锯木断。',
    '失败乃成功之母。',
    '吃一堑,长一智。',
    '笨鸟先飞早入林。',
    '勤能补拙是良训,一分辛劳一分才。',

    '时间是最公平的资源,每个人每天都拥有24小时。',
    '改变从今天开始,行动从现在开始。',
    '每一个优秀的人,都有一段沉默的时光。',
    '不要让昨天占据今天太多的时间。',
    '你的努力,时间会给你答案。',
    '成长就是不断地告别过去的自己。',
    '专注做好一件事,胜过平庸做十件事。',
    '保持热情,保持好奇,保持进步。',
    '每天进步一点点,一年后你会惊讶自己的成长。',
    '自律给你自由,坚持给你奇迹。',

    'Do what you can, with what you have, where you are. — Theodore Roosevelt',
    'The secret of getting ahead is getting started. — Mark Twain',
    "It always seems impossible until it's done. — Nelson Mandela",
    "Don't watch the clock; do what it does. Keep going. — Sam Levenson",
    'The harder you work, the luckier you get. — Gary Player',
    'Success is the sum of small efforts repeated day in and day out. — Robert Collier',
    'The only impossible journey is the one you never begin.',
    "Everything you've ever wanted is on the other side of fear. — George Addair",
    'Start where you are. Use what you have. Do what you can. — Arthur Ashe',
    "Your limitation—it's only your imagination.",

    '人生没有彩排,每天都是现场直播。',
    '态度决定一切,细节决定成败。',
    '机遇偏爱有准备的头脑。',
    '没有绝望的处境,只有对处境绝望的人。',
    '当你停止尝试时,就是失败的时候。',
    '成功的人不是赢在起点,而是赢在转折点。',
    '人生重要的不是所站的位置,而是所朝的方向。',
    '要么读书,要么旅行,身体和灵魂总有一个在路上。',
    '生命太短,没时间留给遗憾。',
    '做你害怕做的事,恐惧就会消失。',

    '志当存高远。 —— 诸葛亮',
    '穷且益坚,不坠青云之志。 —— 王勃',
    '老骥伏枥,志在千里。 —— 曹操',
    '长风破浪会有时,直挂云帆济沧海。 —— 李白',
    '会当凌绝顶,一览众山小。 —— 杜甫',
    '天生我材必有用,千金散尽还复来。 —— 李白',
    '莫等闲,白了少年头,空悲切。 —— 岳飞',
    '先天下之忧而忧,后天下之乐而乐。 —— 范仲淹',
    '人生自古谁无死,留取丹心照汗青。 —— 文天祥',
    '宁为玉碎,不为瓦全。',

    'The only limit to our realization of tomorrow is our doubts of today. — FDR',
    'Act as if what you do makes a difference. It does. — William James',
    'Perseverance is not a long race; it is many short races one after another.',
    'What you get by achieving your goals is not as important as what you become. — Zig Ziglar',
    "You don't have to be great to start, but you have to start to be great. — Zig Ziglar",
    'A journey of a thousand miles begins with a single step. — Lao Tzu',
    "Opportunities don't happen. You create them. — Chris Grosser",
    "Don't be pushed around by your problems. Be led by your dreams.",
    'The way to get started is to quit talking and begin doing. — Walt Disney',
    'If you want to lift yourself up, lift up someone else. — Booker T. Washington',

    // 101-200: 智慧哲理类
    '真正的智慧不是知道一切,而是知道自己无知。 —— 苏格拉底',
    '我思故我在。 —— 笛卡尔',
    '存在先于本质。 —— 萨特',
    '人类的本质是自由的。 —— 萨特',
    '生命不息,奋斗不止。',
    '知识就是力量。 —— 培根',
    '思考是人类最大的乐趣。 —— 布莱希特',
    '沉思是智慧的开始。',
    '经验是最好的老师。',
    '真理往往是简单的。',

    '时间会证明一切。',
    '耐心是一切智慧的源泉。',
    '沉默是智慧的美德。',
    '理智是人类最高贵的品质。',
    '善良是智慧的基础。',
    '谦虚使人进步,骄傲使人落后。',
    '诚实是人生最宝贵的财富。',
    '宽容是最大的美德。',
    '感恩是幸福的源泉。',
    '简单就是终极的复杂。 —— 达芬奇',

    'I think, therefore I am. — Descartes',
    'Know thyself. — Socrates',
    'The unexamined life is not worth living. — Socrates',
    'All we have to decide is what to do with the time that is given us. — Gandalf',
    'The only true wisdom is in knowing you know nothing. — Socrates',
    'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. — Emerson',
    'Life can only be understood backwards; but it must be lived forwards. — Kierkegaard',
    'In the middle of difficulty lies opportunity. — Einstein',
    'The greatest glory in living lies not in never falling, but in rising every time we fall. — Mandela',
    'The purpose of our lives is to be happy. — Dalai Lama',

    '有志者事竟成。',
    '精诚所至,金石为开。',
    '世事洞明皆学问,人情练达即文章。',
    '海纳百川,有容乃大。',
    '静以修身,俭以养德。 —— 诸葛亮',
    '非淡泊无以明志,非宁静无以致远。 —— 诸葛亮',
    '君子坦荡荡,小人长戚戚。 —— 孔子',
    '己欲立而立人,己欲达而达人。 —— 孔子',
    '言必信,行必果。',
    '君子一言,驷马难追。',

    '诚信为本,立德为先。',
    '百善孝为先。',
    '滴水之恩,当涌泉相报。',
    '良药苦口利于病,忠言逆耳利于行。',
    '知足常乐,能忍自安。',
    '心宽体胖,知足常乐。',
    '退一步海阔天空,让三分心平气和。',
    '忍一时风平浪静,退一步海阔天空。',
    '宰相肚里能撑船。',
    '和为贵,忍为高。',

    'Happiness is not something ready made. It comes from your own actions. — Dalai Lama',
    'The best revenge is massive success. — Frank Sinatra',
    "Life is what happens when you're busy making other plans. — John Lennon",
    'Get busy living or get busy dying. — Stephen King',
    'You only live once, but if you do it right, once is enough. — Mae West',
    "Many of life's failures are people who did not realize how close they were to success. — Edison",
    'If you want to live a happy life, tie it to a goal, not to people or things. — Einstein',
    'Never let the fear of striking out keep you from playing the game. — Babe Ruth',
    "Money and success don't change people; they merely amplify what is already there. — Will Smith",
    "Your time is limited, don't waste it living someone else's life. — Steve Jobs",

    '塞翁失马,焉知非福。',
    '祸兮福所倚,福兮祸所伏。 —— 老子',
    '上善若水,水善利万物而不争。 —— 老子',
    '大道至简。',
    '无为而无不为。 —— 老子',
    '知人者智,自知者明。 —— 老子',
    '胜人者有力,自胜者强。 —— 老子',
    '千里之堤,溃于蚁穴。',
    '防微杜渐,未雨绸缪。',
    '临渊羡鱼,不如退而结网。',

    '凡事预则立,不预则废。',
    '工欲善其事,必先利其器。',
    '磨刀不误砍柴工。',
    '好记性不如烂笔头。',
    '读书破万卷,下笔如有神。 —— 杜甫',
    '熟读唐诗三百首,不会作诗也会吟。',
    '温故而知新,可以为师矣。 —— 孔子',
    '学以致用,知行合一。',
    '纸上得来终觉浅,绝知此事要躬行。 —— 陆游',
    '实践是检验真理的唯一标准。',

    'Not how long, but how well you have lived is the main thing. — Seneca',
    'If life were predictable it would cease to be life, and be without flavor. — Eleanor Roosevelt',
    "The whole secret of a successful life is to find out what is one's destiny to do. — Henry Ford",
    'In order to write about life first you must live it. — Ernest Hemingway',
    'Life is either a daring adventure or nothing at all. — Helen Keller',
    'You will face many defeats in life, but never let yourself be defeated. — Maya Angelou',
    'Life is never fair, and perhaps it is a good thing for most of us that it is not. — Oscar Wilde',
    'The only impossible journey is the one you never begin. — Tony Robbins',
    'In this life we cannot do great things. We can only do small things with great love. — Mother Teresa',
    'Only a life lived for others is a life worthwhile. — Albert Einstein',

    // 201-300: 成功奋斗类
    '成功就是从失败到失败,也依然不改热情。 —— 丘吉尔',
    '成功的秘诀就是每天都比别人多努力一点点。',
    '天才是1%的灵感加上99%的汗水。 —— 爱迪生',
    '机会只留给有准备的人。 —— 巴斯德',
    '成功属于那些永不放弃的人。',
    '胜利属于坚持到最后的人。',
    '失败只是成功的序幕。',
    '永不言败,永不放弃。',
    '不经历风雨,怎能见彩虹。',
    '磨难是最好的老师。',

    '困难像弹簧,你弱它就强。',
    '挫折是通向成功的阶梯。',
    '痛苦是成长的代价。',
    '没有比人更高的山,没有比脚更长的路。',
    '世上只有想不通的人,没有走不通的路。',
    '山重水复疑无路,柳暗花明又一村。 —— 陆游',
    '车到山前必有路,船到桥头自然直。',
    '办法总比困难多。',
    '没有过不去的坎,只有过不去的心。',
    '心若在,梦就在,天地之间还有真爱。',

    "I have not failed. I've just found 10,000 ways that won't work. — Edison",
    'Success is not how high you have climbed, but how you make a positive difference to the world. — Roy Bennett',
    "Don't be afraid to give up the good to go for the great. — John D. Rockefeller",
    'I find that the harder I work, the more luck I seem to have. — Thomas Jefferson',
    'Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau',
    'The way to get started is to quit talking and begin doing. — Walt Disney',
    'If you really look closely, most overnight successes took a long time. — Steve Jobs',
    'The secret of success is to do the common thing uncommonly well. — John D. Rockefeller Jr.',
    'Success is walking from failure to failure with no loss of enthusiasm. — Winston Churchill',
    'All progress takes place outside the comfort zone. — Michael John Bobak',

    '不怕慢,就怕站。',
    '只要功夫深,铁杵磨成针。',
    '绳锯木断,水滴石穿。',
    '冰冻三尺,非一日之寒。',
    '台上一分钟,台下十年功。',
    '成功没有捷径,唯有坚持不懈。',
    '路漫漫其修远兮,吾将上下而求索。 —— 屈原',
    '亦余心之所善兮,虽九死其犹未悔。 —— 屈原',
    '为中华之崛起而读书。 —— 周恩来',
    '横眉冷对千夫指,俯首甘为孺子牛。 —— 鲁迅',

    '走自己的路,让别人说去吧。 —— 但丁',
    '生命诚可贵,爱情价更高,若为自由故,两者皆可抛。 —— 裴多菲',
    '给我一个支点,我能撬起整个地球。 —— 阿基米德',
    '我来,我见,我征服。 —— 凯撒',
    '知识改变命运,奋斗成就未来。',
    '今天的努力,明天的实力。',
    '不为失败找借口,只为成功找方法。',
    '有梦想谁都了不起,有勇气就会有奇迹。',
    '心有多大,舞台就有多大。',
    '相信自己,创造奇迹。',

    'The only place where success comes before work is in the dictionary. — Vidal Sassoon',
    'There are no secrets to success. It is the result of preparation, hard work, and learning from failure. — Colin Powell',
    'I never dreamed about success, I worked for it. — Estée Lauder',
    'Success is not final; failure is not fatal: It is the courage to continue that counts. — Winston S. Churchill',
    'The road to success and the road to failure are almost exactly the same. — Colin R. Davis',
    'Success is getting what you want, happiness is wanting what you get. — W. P. Kinsella',
    "Don't aim for success if you want it; just do what you love and believe in. — David Frost",
    'Success is not in what you have, but who you are. — Bo Bennett',
    'Fall seven times and stand up eight. — Japanese Proverb',
    'A successful man is one who can lay a firm foundation with the bricks others have thrown at him. — David Brinkley',

    '胜不骄,败不馁。',
    '谦虚谨慎,戒骄戒躁。',
    '骄傲使人落后,虚心使人进步。',
    '满招损,谦受益。',
    '虚心竹有低头叶,傲骨梅无仰面花。',
    '良言一句三冬暖,恶语伤人六月寒。',
    '一言既出,驷马难追。',
    '说到做到,言出必行。',
    '一诺千金。',
    '轻诺必寡信。 —— 老子',

    '言多必失,祸从口出。',
    '沉默是金,雄辩是银。',
    '行动胜于雄辩。',
    '事实胜于雄辩。',
    '空谈误国,实干兴邦。',
    '一分部署,九分落实。',
    '说一千道一万,不如脚踏实地干。',
    '喊破嗓子不如甩开膀子。',
    '光说不练假把式,光练不说傻把式,能说会练真把式。',
    '实干兴邦,空谈误国。',

    // 301-400: 学习成长类
    '学习如逆水行舟,不进则退。',
    '活到老,学到老。',
    '书籍是人类进步的阶梯。 —— 高尔基',
    '读书使人充实,思考使人深邃,交谈使人清醒。 —— 富兰克林',
    '读一本好书,就是和许多高尚的人谈话。 —— 歌德',
    '书是全世界的营养品。 —— 莎士比亚',
    '腹有诗书气自华。 —— 苏轼',
    '立身以立学为先,立学以读书为本。 —— 欧阳修',
    '黑发不知勤学早,白首方悔读书迟。 —— 颜真卿',
    '书山有路勤为径,学海无涯苦作舟。',

    '学如不及,犹恐失之。',
    '学而时习之,不亦说乎。 —— 孔子',
    '温故而知新。 —— 孔子',
    '学而不厌,诲人不倦。 —— 孔子',
    '敏而好学,不耻下问。 —— 孔子',
    '学无止境。',
    '学海无涯。',
    '博学之,审问之,慎思之,明辨之,笃行之。',
    '读书百遍,其义自见。',
    '书读百遍,其义自现。',

    'Education is the most powerful weapon which you can use to change the world. — Nelson Mandela',
    'The beautiful thing about learning is that nobody can take it away from you. — B.B. King',
    'Education is not preparation for life; education is life itself. — John Dewey',
    'The more that you read, the more things you will know. — Dr. Seuss',
    'Live as if you were to die tomorrow. Learn as if you were to live forever. — Gandhi',
    'An investment in knowledge pays the best interest. — Benjamin Franklin',
    'Anyone who stops learning is old, whether at twenty or eighty. — Henry Ford',
    'Learning never exhausts the mind. — Leonardo da Vinci',
    'The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice. — Brian Herbert',
    'Tell me and I forget, teach me and I may remember, involve me and I learn. — Benjamin Franklin',

    '好学近乎知,力行近乎仁,知耻近乎勇。',
    '博学而笃志,切问而近思。',
    '学贵有疑,小疑则小进,大疑则大进。',
    '学问之道无他,求其放心而已矣。 —— 孟子',
    '尽信书,则不如无书。 —— 孟子',
    '读万卷书,行万里路。',
    '纸上得来终觉浅,绝知此事要躬行。',
    '实践出真知。',
    '百闻不如一见,百见不如一干。',
    '光说不练假把式。',

    '知识就是财富。',
    '知识改变命运。',
    '学习改变人生。',
    '读书改变命运,学习成就未来。',
    '书中自有黄金屋,书中自有颜如玉。',
    '万般皆下品,唯有读书高。',
    '书到用时方恨少,事非经过不知难。',
    '少年易学老难成,一寸光阴不可轻。 —— 朱熹',
    '盛年不重来,一日难再晨。 —— 陶渊明',
    '明日复明日,明日何其多。',

    'The expert in anything was once a beginner. — Helen Hayes',
    'Learning is not attained by chance; it must be sought for with ardor and diligence. — Abigail Adams',
    'Wisdom is not a product of schooling but of the lifelong attempt to acquire it. — Einstein',
    "Develop a passion for learning. If you do, you will never cease to grow. — Anthony J. D'Angelo",
    'The only person who is educated is the one who has learned how to learn and change. — Carl Rogers',
    'Education is the passport to the future, for tomorrow belongs to those who prepare for it today. — Malcolm X',
    'Intelligence plus character—that is the goal of true education. — Martin Luther King Jr.',
    'Change is the end result of all true learning. — Leo Buscaglia',
    "You don't understand anything until you learn it more than one way. — Marvin Minsky",
    'I am always doing that which I cannot do, in order that I may learn how to do it. — Pablo Picasso',

    '学如弓弩,才如箭镞。',
    '才须学也,非学无以广才。 —— 诸葛亮',
    '非学无以成才。',
    '玉不琢,不成器;人不学,不知义。',
    '少而好学,如日出之阳;壮而好学,如日中之光;老而好学,如炳烛之明。',
    '学习如春起之苗,不见其增,日有所长。',
    '学如逆水行舟,不进则退。',
    '学习永无止境。',
    '知识无涯,学无止境。',
    '学到老,活到老。',

    // 401-500: 时间管理类
    '时间就是生命,浪费时间就是浪费生命。',
    '一寸光阴一寸金,寸金难买寸光阴。',
    '时间就是金钱,效率就是生命。',
    '浪费时间等于浪费生命。',
    '珍惜时间就是珍惜生命。',
    '时不我待,岁月不居。',
    '光阴似箭,日月如梭。',
    '白驹过隙,岁月如梭。',
    '时光荏苒,岁月如流。',
    '岁月不待人。',

    '时间一去不复返。',
    '失去的时间永远找不回来。',
    '昨日不可追,今日须把握。',
    '今日事今日毕。',
    '明日复明日,明日何其多。',
    '莫等闲,白了少年头。',
    '黑发不知勤学早,白首方悔读书迟。',
    '少壮不努力,老大徒伤悲。',
    '花有重开日,人无再少年。',
    '盛年不重来,一日难再晨。',

    'Time is money. — Benjamin Franklin',
    'Lost time is never found again. — Benjamin Franklin',
    'Time flies over us, but leaves its shadow behind. — Nathaniel Hawthorne',
    'The trouble is, you think you have time. — Buddha',
    'Time is what we want most, but what we use worst. — William Penn',
    "Don't wait. The time will never be just right. — Napoleon Hill",
    'Yesterday is gone. Tomorrow has not yet come. We have only today. — Mother Teresa',
    'Time you enjoy wasting is not wasted time. — Marthe Troly-Curtin',
    "The bad news is time flies. The good news is you're the pilot. — Michael Altshuler",
    'Time is the most valuable thing a man can spend. — Theophrastus',

    '合理安排时间,就等于节约时间。',
    '善于利用时间的人,永远找得到充裕的时间。',
    '时间就像海绵里的水,只要愿挤,总还是有的。 —— 鲁迅',
    '把握今天,胜过两个明天。',
    '今天能做的事,不要拖到明天。',
    '拖延是时间的窃贼。',
    '拖延是成功的大敌。',
    '效率是生命的一部分。',
    '高效工作,快乐生活。',
    '用有限的时间,创造无限的价值。',

    '时间管理就是人生管理。',
    '管理好时间,就是管理好人生。',
    '时间分配得当,就是走向成功。',
    '珍惜每一分钟,创造每一个奇迹。',
    '时间的价值在于充分利用。',
    '浪费时间是所有支出中最奢侈及最昂贵的。',
    '合理利用时间,提高工作效率。',
    '时间就是能力,效率就是生命。',
    '珍惜时间,创造价值。',
    '时光不可倒流,唯有珍惜当下。',

    "Your time is limited, so don't waste it living someone else's life. — Steve Jobs",
    "The key is not to prioritize what's on your schedule, but to schedule your priorities. — Stephen Covey",
    'Time management is life management. — Robin Sharma',
    'Until we can manage time, we can manage nothing else. — Peter Drucker',
    'The shorter way to do many things is to do only one thing at a time. — Mozart',
    'One always has time enough, if one will apply it well. — Johann Wolfgang von Goethe',
    'Time is a created thing. To say "I don\'t have time" is like saying, "I don\'t want to." — Lao Tzu',
    "It's not enough to be busy, so are the ants. The question is, what are we busy about? — Thoreau",
    "Don't be fooled by the calendar. There are only as many days in the year as you make use of. — Charles Richards",
    'Time = life; therefore, waste your time and waste your life, or master your time and master your life. — Alan Lakein',

    '一年之计在于春,一日之计在于晨。',
    '早起的鸟儿有虫吃。',
    '时间在于计划,成功在于执行。',
    '计划赶不上变化,变化赶不上电话。',
    '凡事预则立,不预则废。',
    '有计划不忙,有准备不慌。',
    '计划是成功的前提。',
    '好的开始是成功的一半。',
    '机会总是留给有准备的人。',
    '不打无准备之仗。',

    // 501-600: 人际关系类
    '朋友多了路好走。',
    '在家靠父母,出门靠朋友。',
    '患难见真情。',
    '路遥知马力,日久见人心。',
    '真金不怕火炼,患难识知己。',
    '酒逢知己千杯少,话不投机半句多。',
    '人生得一知己足矣。 —— 鲁迅',
    '海内存知己,天涯若比邻。 —— 王勃',
    '相识满天下,知心能几人。',
    '人生贵相知,何必金与钱。',

    '千金易得,知己难求。',
    '君子之交淡如水,小人之交甘若醴。',
    '近朱者赤,近墨者黑。',
    '与善人居,如入兰芷之室,久而不闻其香。',
    '与不善人居,如入鲍鱼之肆,久而不闻其臭。',
    '择善而从,不善而改之。',
    '三人行,必有我师焉,择其善者而从之,其不善者而改之。',
    '闻道有先后,术业有专攻。 —— 韩愈',
    '尺有所短,寸有所长。',
    '金无足赤,人无完人。',

    'A friend in need is a friend indeed.',
    'True friendship is a plant of slow growth. — George Washington',
    'Friendship is born at that moment when one person says to another, "What! You too?" — C.S. Lewis',
    'A real friend is one who walks in when the rest of the world walks out. — Walter Winchell',
    'Friendship is the only cement that will ever hold the world together. — Woodrow Wilson',
    'The greatest gift of life is friendship. — Hubert H. Humphrey',
    'A true friend never gets in your way unless you happen to be going down. — Arnold Glasow',
    'Friendship multiplies the good of life and divides the evil. — Baltasar Gracian',
    'In the sweetness of friendship let there be laughter and sharing of pleasures. — Khalil Gibran',
    'The language of friendship is not words but meanings. — Henry David Thoreau',

    '爱人者,人恒爱之;敬人者,人恒敬之。 —— 孟子',
    '投我以桃,报之以李。',
    '礼尚往来,来而不往非礼也。',
    '赠人玫瑰,手有余香。',
    '善待他人,就是善待自己。',
    '帮助别人,快乐自己。',
    '予人方便,与己方便。',
    '得道多助,失道寡助。',
    '众人拾柴火焰高。',
    '团结就是力量。',

    '一个篱笆三个桩,一个好汉三个帮。',
    '单丝不成线,独木不成林。',
    '三个臭皮匠,顶个诸葛亮。',
    '人心齐,泰山移。',
    '团结一心,其利断金。',
    '和气生财,家和万事兴。',
    '家和万事兴。',
    '百善孝为先。',
    '父母在,不远游,游必有方。',
    '羊有跪乳之恩,鸦有反哺之义。',

    'No man is an island. — John Donne',
    'Alone we can do so little; together we can do so much. — Helen Keller',
    'Coming together is a beginning; keeping together is progress; working together is success. — Henry Ford',
    'Unity is strength. When there is teamwork and collaboration, wonderful things can be achieved. — Mattie Stepanek',
    'Teamwork makes the dream work. — John C. Maxwell',
    'Individual commitment to a group effort—that is what makes a team work. — Vince Lombardi',
    "Great things in business are never done by one person; they're done by a team of people. — Steve Jobs",
    'If everyone is moving forward together, then success takes care of itself. — Henry Ford',
    'The strength of the team is each individual member. The strength of each member is the team. — Phil Jackson',
    'Cooperation is the thorough conviction that nobody can get there unless everybody gets there. — Virginia Burden',

    '己所不欲,勿施于人。',
    '将心比心,以心换心。',
    '推己及人,设身处地。',
    '换位思考,理解他人。',
    '宽以待人,严以律己。',
    '严于律己,宽以待人。',
    '责人不如责己,怨人不如怨己。',
    '静坐常思己过,闲谈莫论人非。',
    '金无足赤,人无完人,包容他人就是包容自己。',
    '尊重他人就是尊重自己。',

    // 601-700: 态度心态类
    '态度决定一切。',
    '态度决定高度。',
    '心态决定命运。',
    '积极的心态,成功的一半。',
    '悲观的人在机会中看到困难,乐观的人在困难中看到机会。',
    '乐观者看到的是机会,悲观者看到的是障碍。',
    '心中有阳光,脚下有力量。',
    '积极心态迎接每一天。',
    '笑对人生,乐观向上。',
    '微笑是最美的语言。',

    '保持积极的心态,拥抱美好的明天。',
    '心有多大,舞台就有多大。',
    '格局决定结局,态度决定高度。',
    '改变态度,改变人生。',
    '好的心态是成功的基石。',
    '积极的心态带来积极的人生。',
    '心态平和,万事顺遂。',
    '心平气和,海阔天空。',
    '淡定从容,宠辱不惊。',
    '不以物喜,不以己悲。 —— 范仲淹',

    'Your attitude, not your aptitude, will determine your altitude. — Zig Ziglar',
    'A positive attitude can really make dreams come true. — David Bailey',
    'The only disability in life is a bad attitude. — Scott Hamilton',
    'Attitude is a little thing that makes a big difference. — Winston Churchill',
    "Wherever you go, no matter what the weather, always bring your own sunshine. — Anthony J. D'Angelo",
    'A negative mind will never give you a positive life.',
    'Positive thinking will let you do everything better than negative thinking will. — Zig Ziglar',
    'Keep your face always toward the sunshine—and shadows will fall behind you. — Walt Whitman',
    "Once you replace negative thoughts with positive ones, you'll start having positive results. — Willie Nelson",
    'Positive anything is better than negative nothing. — Elbert Hubbard',

    '塞翁失马,焉知非福。',
    '祸兮福所倚,福兮祸所伏。',
    '失败是成功之母。',
    '挫折是人生的财富。',
    '困难是锻炼人的最好机会。',
    '逆境造就人才。',
    '宝剑锋从磨砺出,梅花香自苦寒来。',
    '天将降大任于斯人也,必先苦其心志,劳其筋骨。 —— 孟子',
    '吃得苦中苦,方为人上人。',
    '不经一番寒彻骨,怎得梅花扑鼻香。',

    '苦尽甘来。',
    '否极泰来。',
    '守得云开见月明。',
    '雨过天晴。',
    '阳光总在风雨后。',
    '黎明前的黑暗最黑暗。',
    '坚持到底就是胜利。',
    '成功往往在于再坚持一下。',
    '永不言弃。',
    '只要不放弃,就有希望。',

    "Whether you think you can or you think you can't, you're right. — Henry Ford",
    'Life is 10% what happens to you and 90% how you react to it. — Charles R. Swindoll',
    'With the new day comes new strength and new thoughts. — Eleanor Roosevelt',
    'Optimism is the faith that leads to achievement. — Helen Keller',
    'Pessimism leads to weakness, optimism to power. — William James',
    'In every day, there are 1,440 minutes. That means we have 1,440 daily opportunities to make a positive impact. — Les Brown',
    'The positive thinker sees the invisible, feels the intangible, and achieves the impossible. — Winston Churchill',
    'Yesterday is not ours to recover, but tomorrow is ours to win or lose. — Lyndon B. Johnson',
    "You can't go back and change the beginning, but you can start where you are and change the ending. — C.S. Lewis",
    "It's not what happens to you, but how you react to it that matters. — Epictetus",

    '知足常乐。',
    '比上不足,比下有余。',
    '珍惜拥有,感恩生活。',
    '感恩的心,快乐的人生。',
    '懂得感恩,学会珍惜。',
    '感恩每一天,珍惜每一刻。',
    '心存感激,幸福常在。',
    '感恩父母,孝敬长辈。',
    '滴水之恩,当涌泉相报。',
    '知恩图报,做人之本。',

    // 701-800: 梦想目标类
    '心中有梦想,脚下有力量。',
    '有梦想谁都了不起,有勇气就会有奇迹。',
    '梦想是成功的起点。',
    '没有梦想,何必远方。',
    '梦想还是要有的,万一实现了呢。',
    '敢于梦想,勇于追求。',
    '不忘初心,方得始终。',
    '初心易得,始终难守。',
    '坚守初心,追逐梦想。',
    '理想是指路的明灯。',

    '有理想的人生才有方向。',
    '志当存高远。',
    '雄关漫道真如铁,而今迈步从头越。 —— 毛泽东',
    '红军不怕远征难,万水千山只等闲。 —— 毛泽东',
    '世上无难事,只要肯登攀。 —— 毛泽东',
    '为有牺牲多壮志,敢教日月换新天。 —— 毛泽东',
    '数风流人物,还看今朝。 —— 毛泽东',
    '俱往矣,数风流人物,还看今朝。 —— 毛泽东',
    '一万年太久,只争朝夕。 —— 毛泽东',
    '自信人生二百年,会当水击三千里。 —— 毛泽东',

    "A dream doesn't become reality through magic; it takes sweat, determination and hard work. — Colin Powell",
    'The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt',
    'Dream big and dare to fail. — Norman Vaughan',
    'All our dreams can come true, if we have the courage to pursue them. — Walt Disney',
    'The only thing worse than starting something and failing is not starting something. — Seth Godin',
    'If you can dream it, you can do it. — Walt Disney',
    "Dreams don't work unless you do. — John C. Maxwell",
    'Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly. — Langston Hughes',
    'You are never too old to set another goal or to dream a new dream. — C.S. Lewis',
    'The biggest adventure you can take is to live the life of your dreams. — Oprah Winfrey',

    '目标明确,方向清晰。',
    '有目标才有动力。',
    '目标是前进的方向。',
    '设定目标,勇往直前。',
    '目标决定高度。',
    '有目标的人生才有意义。',
    '明确目标,脚踏实地。',
    '目标要高,但不要好高骛远。',
    '分解目标,逐步实现。',
    '一步一个脚印,稳步前进。',

    '千里之行,始于足下。',
    '不积跬步,无以至千里。',
    '积少成多,聚沙成塔。',
    '集腋成裘,积少成多。',
    '滴水穿石,非一日之功。',
    '冰冻三尺,非一日之寒。',
    '罗马不是一天建成的。',
    '万丈高楼平地起。',
    '九层之台,起于垒土。',
    '合抱之木,生于毫末。',

    'Setting goals is the first step in turning the invisible into the visible. — Tony Robbins',
    'A goal without a plan is just a wish. — Antoine de Saint-Exupéry',
    'You should set goals beyond your reach so you always have something to live for. — Ted Turner',
    'The trouble with not having a goal is that you can spend your life running and never arrive. — Bill Copeland',
    'Goals are dreams with deadlines. — Diana Scharf',
    'What you get by achieving your goals is not as important as what you become by achieving your goals. — Henry David Thoreau',
    'Goals transform a random walk into a chase. — Mihaly Csikszentmihalyi',
    'By recording your dreams and goals on paper, you set in motion the process of becoming the person you most want to be. — Mark Victor Hansen',
    'You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals. — Booker T. Washington',
    'If you want to be happy, set a goal that commands your thoughts, liberates your energy and inspires your hopes. — Andrew Carnegie',

    '坚持就是胜利。',
    '贵在坚持,难在坚持,成在坚持。',
    '坚持到底,永不放弃。',
    '不抛弃,不放弃。',
    '锲而不舍,金石可镂。',
    '精诚所至,金石为开。',
    '水滴石穿,绳锯木断。',
    '持之以恒,必有所成。',
    '坚持不懈,终会成功。',
    '功到自然成。',

    // 801-900: 创新变革类
    '创新是发展的第一动力。',
    '创新引领未来。',
    '创新改变世界。',
    '创新无止境。',
    '敢为人先,勇于创新。',
    '思路决定出路,创新决定未来。',
    '创新是企业的生命。',
    '不创新,则灭亡。',
    '创新是民族进步的灵魂。',
    '科技创新,引领未来。',

    '改革创新,与时俱进。',
    '求新求变,开拓进取。',
    '创新思维,突破自我。',
    '打破常规,勇于突破。',
    '突破思维定势,创新工作方法。',
    '解放思想,更新观念。',
    '思想有多远,就能走多远。',
    '观念一变天地宽。',
    '改变思维,改变人生。',
    '换个角度,海阔天空。',

    'Innovation distinguishes between a leader and a follower. — Steve Jobs',
    'The secret to change is to focus all of your energy not on fighting the old, but on building the new. — Socrates',
    'Innovation is the ability to see change as an opportunity, not a threat.',
    'If you always do what you always did, you will always get what you always got. — Albert Einstein',
    'The definition of insanity is doing the same thing over and over again and expecting different results. — Einstein',
    'Innovation is taking two things that exist and putting them together in a new way. — Tom Freston',
    'The best way to predict the future is to create it. — Peter Drucker',
    "You can't use up creativity. The more you use, the more you have. — Maya Angelou",
    'Creativity is intelligence having fun. — Albert Einstein',
    'The true sign of intelligence is not knowledge but imagination. — Albert Einstein',

    '变则通,通则久。',
    '穷则变,变则通,通则久。',
    '物竞天择,适者生存。',
    '适应变化,才能生存。',
    '变化是永恒的主题。',
    '变是唯一的不变。',
    '以不变应万变。',
    '万变不离其宗。',
    '应变能力是生存之本。',
    '拥抱变化,迎接挑战。',

    '改变从自己开始。',
    '改变自己,影响他人。',
    '与其抱怨,不如改变。',
    '改变不了环境,就改变自己。',
    '改变不了别人,就改变自己。',
    '改变态度,改变人生。',
    '改变思维,改变命运。',
    '改变习惯,改变未来。',
    '从今天开始改变。',
    '改变永远不会太迟。',

    'Change is the law of life. And those who look only to the past or present are certain to miss the future. — JFK',
    "If you don't like something, change it. If you can't change it, change your attitude. — Maya Angelou",
    'Progress is impossible without change, and those who cannot change their minds cannot change anything. — Shaw',
    'The only way to make sense out of change is to plunge into it, move with it, and join the dance. — Alan Watts',
    'Everyone thinks of changing the world, but no one thinks of changing himself. — Leo Tolstoy',
    'Change your thoughts and you change your world. — Norman Vincent Peale',
    'If you want something you have never had, you must be willing to do something you have never done. — Jefferson',
    'The secret of change is to focus all of your energy not on fighting the old but on building the new. — Socrates',
    'Change will not come if we wait for some other person or some other time. — Barack Obama',
    'They always say time changes things, but you actually have to change them yourself. — Andy Warhol',

    '不破不立,破旧立新。',
    '革故鼎新。',
    '推陈出新。',
    '去旧迎新。',
    '吐故纳新。',
    '更新换代。',
    '与时俱进。',
    '日新月异。',
    '日日新,又日新。',
    '苟日新,日日新,又日新。',

    // 901-1000: 综合启示类
    '人生如戏,戏如人生。',
    '世界那么大,我想去看看。',
    '生活不止眼前的苟且,还有诗和远方。',
    '人生没有彩排,每天都是直播。',
    '人生就像一场马拉松。',
    '人生就是一场修行。',
    '活在当下,珍惜眼前。',
    '过好当下,不负时光。',
    '昨天已去,明天未来,只有今天。',
    '把握今天,创造明天。',

    '人生苦短,及时行乐。',
    '人生得意须尽欢。',
    '人生难得几回醉。',
    '今朝有酒今朝醉。',
    '何不潇洒走一回。',
    '人生豪迈,重头再来。',
    '跌倒了再爬起来。',
    '从哪里跌倒,就从哪里爬起来。',
    '失败了并不可怕,可怕的是不敢再试。',
    '重要的不是失败,而是从失败中学到什么。',

    'Life is really simple, but we insist on making it complicated. — Confucius',
    "In three words I can sum up everything I've learned about life: it goes on. — Robert Frost",
    "Life is what happens when you're busy making other plans. — John Lennon",
    'The purpose of life is not to be happy. It is to be useful, honorable, compassionate. — Ralph Waldo Emerson',
    "Life isn't about finding yourself. Life is about creating yourself. — George Bernard Shaw",
    'The two most important days in your life are the day you are born and the day you find out why. — Mark Twain',
    'Life is 10% what happens to me and 90% of how I react to it. — Charles Swindoll',
    'An unexamined life is not worth living. — Socrates',
    'Turn your wounds into wisdom. — Oprah Winfrey',
    'The greatest glory in living lies not in never falling, but in rising every time we fall. — Nelson Mandela',

    '人生处处是课堂。',
    '生活是最好的老师。',
    '实践出真知。',
    '吃一堑,长一智。',
    '前事不忘,后事之师。',
    '前车之鉴,后车之师。',
    '历史是一面镜子。',
    '以史为鉴,可以知兴替。',
    '鉴往知来。',
    '温故知新。',

    '活到老,学到老,改到老。',
    '人无完人,金无足赤。',
    '人非圣贤,孰能无过。',
    '知错能改,善莫大焉。',
    '亡羊补牢,为时不晚。',
    '过而能改,善莫大焉。',
    '有则改之,无则加勉。',
    '闻过则喜。',
    '虚心接受批评。',
    '批评是进步的阶梯。',

    'The unexamined life is not worth living. — Socrates',
    'Life can only be understood backwards; but it must be lived forwards. — Søren Kierkegaard',
    'The good life is one inspired by love and guided by knowledge. — Bertrand Russell',
    'Life is a succession of lessons which must be lived to be understood. — Helen Keller',
    'Life is not a problem to be solved, but a reality to be experienced. — Søren Kierkegaard',
    'The meaning of life is to find your gift. The purpose of life is to give it away. — Pablo Picasso',
    'Life is short, and it is up to you to make it sweet. — Sarah Louise Delany',
    "In the end, it's not the years in your life that count. It's the life in your years. — Abraham Lincoln",
    'Life is like riding a bicycle. To keep your balance, you must keep moving. — Albert Einstein',
    'May you live every day of your life. — Jonathan Swift',

    '平平淡淡才是真。',
    '平凡中见伟大。',
    '细节决定成败。',
    '成大事者不拘小节,但细节往往决定成败。',
    '天下大事,必作于细。',
    '天下难事,必作于易;天下大事,必作于细。',
    '千里之堤,溃于蚁穴。',
    '差之毫厘,谬以千里。',
    '小心驶得万年船。',
    '谨慎小心,百年不倒。',

    '做人要厚道。',
    '厚德载物。',
    '君子以厚德载物。',
    '品德高尚,才能服人。',
    '德行天下。',
    '德才兼备。',
    '才者德之资,德者才之帅。',
    '有德有才是正品,有德无才是次品,无德有才是毒品。',
    '做事先做人。',
    '先成人,后成才。',

    'Character is like a tree and reputation like a shadow. — Abraham Lincoln',
    'Be more concerned with your character than your reputation. — John Wooden',
    "Excellence is not a skill, it's an attitude. — Ralph Marston",
    'Quality is not an act, it is a habit. — Aristotle',
    'We are what we repeatedly do. Excellence, then, is not an act, but a habit. — Aristotle',
    'The only way to do great work is to love what you do. — Steve Jobs',
    'Quality means doing it right when no one is looking. — Henry Ford',
    'Strive not to be a success, but rather to be of value. — Albert Einstein',
    'Try not to become a man of success. Rather become a man of value. — Albert Einstein',
    'The best preparation for tomorrow is doing your best today. — H. Jackson Brown Jr.',

    '路在脚下,梦在前方。',
    '脚踏实地,仰望星空。',
    '既要脚踏实地,又要仰望星空。',
    '走好每一步,登上每一级。',
    '一步一个脚印。',
    '稳扎稳打,步步为营。',
    '不积跬步,无以至千里;不积小流,无以成江海。',
    '勿以善小而不为,勿以恶小而为之。',
    '莫以恶小而为之,莫以善小而不为。',
    '行胜于言。',
  ];

  /// 根据日期获取对应的名言
  static String getQuote(int dayOfMonth) {
    // 1-31号对应0-30,循环1000句
    final index = (dayOfMonth - 1) % quotes.length;
    return quotes[index];
  }

  /// 获取随机名言
  static String getRandomQuote() {
    final random = DateTime.now().millisecondsSinceEpoch % quotes.length;
    return quotes[random];
  }
}
