import 'package:flutter/material.dart';
import 'package:todolist/src/domain/entities/task.dart';
import 'package:todolist/src/domain/entities/task_template.dart';

/// 预设任务模板数据
class PresetTemplates {
  PresetTemplates._();

  /// 所有预设模板
  static List<TaskTemplate> get all => [
        ...fitnessTemplates,
        ...workTemplates,
        ...lifeTemplates,
        ...healthTemplates,
        ...socialTemplates,
        ...financeTemplates,
      ];

  /// 健身运动模板
  static List<TaskTemplate> get fitnessTemplates => [
        // 力量训练 - 三大项
        _createTemplate(
          id: 'fitness_squat',
          title: '深蹲训练',
          description: '进行3-5组深蹲训练，每组8-12次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.medium,
          estimatedMinutes: 30,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '下肢'],
        ),
        _createTemplate(
          id: 'fitness_bench_press',
          title: '卧推训练',
          description: '进行3-5组杠铃卧推，每组8-12次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.medium,
          estimatedMinutes: 30,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '胸部'],
        ),
        _createTemplate(
          id: 'fitness_deadlift',
          title: '硬拉训练',
          description: '进行3-5组硬拉，每组6-10次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.medium,
          estimatedMinutes: 30,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '背部'],
        ),

        // 深蹲变式
        _createTemplate(
          id: 'fitness_front_squat',
          title: '颈前深蹲',
          description: '颈前深蹲3-4组，每组8-10次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 25,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '下肢'],
        ),
        _createTemplate(
          id: 'fitness_goblet_squat',
          title: '高脚杯深蹲',
          description: '高脚杯深蹲3-4组，每组12-15次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 20,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '下肢'],
        ),

        // 卧推变式
        _createTemplate(
          id: 'fitness_incline_press',
          title: '上斜卧推',
          description: '上斜卧推3-4组，每组8-12次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 25,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '胸部'],
        ),
        _createTemplate(
          id: 'fitness_dumbbell_press',
          title: '哑铃卧推',
          description: '哑铃卧推3-4组，每组10-12次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 25,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '胸部'],
        ),

        // 硬拉变式
        _createTemplate(
          id: 'fitness_romanian_deadlift',
          title: '罗马尼亚硬拉',
          description: '罗马尼亚硬拉3-4组，每组8-10次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 25,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '背部', '腿部'],
        ),
        _createTemplate(
          id: 'fitness_sumo_deadlift',
          title: '相扑硬拉',
          description: '相扑硬拉3-4组，每组6-10次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 25,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '背部', '腿部'],
        ),

        // 上肢训练
        _createTemplate(
          id: 'fitness_pull_up',
          title: '引体向上',
          description: '引体向上3-5组，每组做到力竭',
          category: TemplateCategory.fitness,
          priority: TaskPriority.medium,
          estimatedMinutes: 20,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '背部', '手臂'],
        ),
        _createTemplate(
          id: 'fitness_shoulder_press',
          title: '肩推训练',
          description: '杠铃或哑铃肩推3-4组，每组8-12次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.medium,
          estimatedMinutes: 25,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '肩部'],
        ),
        _createTemplate(
          id: 'fitness_bicep_curl',
          title: '二头弯举',
          description: '哑铃或杠铃弯举3-4组，每组10-15次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 20,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '手臂'],
        ),
        _createTemplate(
          id: 'fitness_tricep_extension',
          title: '三头臂屈伸',
          description: '双杠臂屈伸或绳索下压3-4组，每组10-15次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 20,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '手臂'],
        ),
        _createTemplate(
          id: 'fitness_pushup',
          title: '俯卧撑训练',
          description: '标准俯卧撑3-5组，每组15-25次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 15,
          icon: Icons.fitness_center,
          tags: ['健身', '自重训练', '胸部', '手臂'],
        ),

        // 下肢训练
        _createTemplate(
          id: 'fitness_lunge',
          title: '箭步蹲',
          description: '哑铃箭步蹲3-4组，每侧10-12次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.medium,
          estimatedMinutes: 20,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '下肢'],
        ),
        _createTemplate(
          id: 'fitness_leg_press',
          title: '腿举训练',
          description: '器械腿举3-4组，每组12-15次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 20,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '下肢'],
        ),
        _createTemplate(
          id: 'fitness_leg_curl',
          title: '腿弯举',
          description: '俯卧腿弯举3-4组，每组12-15次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 15,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '腿部'],
        ),
        _createTemplate(
          id: 'fitness_leg_extension',
          title: '腿屈伸',
          description: '坐姿腿屈伸3-4组，每组12-15次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 15,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '腿部'],
        ),
        _createTemplate(
          id: 'fitness_calf_raise',
          title: '提踵训练',
          description: '站姿提踵4组，每组15-20次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 15,
          icon: Icons.fitness_center,
          tags: ['健身', '力量训练', '小腿'],
        ),

        // 有氧运动
        _createTemplate(
          id: 'fitness_running',
          title: '跑步训练',
          description: '慢跑或变速跑30-45分钟',
          category: TemplateCategory.fitness,
          priority: TaskPriority.high,
          estimatedMinutes: 40,
          icon: Icons.directions_run,
          tags: ['健身', '有氧运动', '跑步'],
        ),
        _createTemplate(
          id: 'fitness_swimming',
          title: '游泳训练',
          description: '游泳30-45分钟，多种泳姿交替',
          category: TemplateCategory.fitness,
          priority: TaskPriority.medium,
          estimatedMinutes: 45,
          icon: Icons.pool,
          tags: ['健身', '有氧运动', '游泳'],
        ),
        _createTemplate(
          id: 'fitness_cycling',
          title: '骑行训练',
          description: '动感单车或户外骑行40-60分钟',
          category: TemplateCategory.fitness,
          priority: TaskPriority.medium,
          estimatedMinutes: 50,
          icon: Icons.directions_bike,
          tags: ['健身', '有氧运动', '骑行'],
        ),
        _createTemplate(
          id: 'fitness_elliptical',
          title: '椭圆机训练',
          description: '椭圆机30-40分钟，保持中等强度',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 35,
          icon: Icons.fitness_center,
          tags: ['健身', '有氧运动'],
        ),
        _createTemplate(
          id: 'fitness_jump_rope',
          title: '跳绳训练',
          description: '跳绳15-20分钟，可分组进行',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 20,
          icon: Icons.fitness_center,
          tags: ['健身', '有氧运动', '跳绳'],
        ),
        _createTemplate(
          id: 'fitness_rowing',
          title: '划船机训练',
          description: '划船机20-30分钟，全身有氧',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 25,
          icon: Icons.rowing,
          tags: ['健身', '有氧运动'],
        ),

        // 核心训练
        _createTemplate(
          id: 'fitness_plank',
          title: '平板支撑',
          description: '平板支撑3-5组，每组30-60秒',
          category: TemplateCategory.fitness,
          priority: TaskPriority.medium,
          estimatedMinutes: 15,
          icon: Icons.fitness_center,
          tags: ['健身', '核心训练', '腹部'],
        ),
        _createTemplate(
          id: 'fitness_crunch',
          title: '卷腹训练',
          description: '卷腹3-4组，每组15-25次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.medium,
          estimatedMinutes: 15,
          icon: Icons.fitness_center,
          tags: ['健身', '核心训练', '腹部'],
        ),
        _createTemplate(
          id: 'fitness_russian_twist',
          title: '俄罗斯转体',
          description: '俄罗斯转体3-4组，每组20-30次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 15,
          icon: Icons.fitness_center,
          tags: ['健身', '核心训练', '腹部'],
        ),
        _createTemplate(
          id: 'fitness_leg_raise',
          title: '悬垂举腿',
          description: '悬垂举腿3-4组，每组10-15次',
          category: TemplateCategory.fitness,
          priority: TaskPriority.medium,
          estimatedMinutes: 15,
          icon: Icons.fitness_center,
          tags: ['健身', '核心训练', '腹部'],
        ),

        // 柔韧性训练
        _createTemplate(
          id: 'fitness_yoga',
          title: '瑜伽练习',
          description: '瑜伽课程或自主练习45-60分钟',
          category: TemplateCategory.fitness,
          priority: TaskPriority.medium,
          estimatedMinutes: 50,
          icon: Icons.self_improvement,
          tags: ['健身', '柔韧性', '瑜伽'],
        ),
        _createTemplate(
          id: 'fitness_stretching',
          title: '拉伸训练',
          description: '全身拉伸15-20分钟，各部位充分拉伸',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 20,
          icon: Icons.accessibility_new,
          tags: ['健身', '柔韧性', '拉伸'],
        ),
        _createTemplate(
          id: 'fitness_foam_rolling',
          title: '泡沫轴放松',
          description: '使用泡沫轴放松全身肌肉10-15分钟',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 15,
          icon: Icons.spa,
          tags: ['健身', '恢复', '放松'],
        ),

        // 日常健身习惯
        _createTemplate(
          id: 'fitness_warmup',
          title: '热身运动',
          description: '训练前热身10分钟，激活身体',
          category: TemplateCategory.fitness,
          priority: TaskPriority.high,
          estimatedMinutes: 10,
          icon: Icons.directions_run,
          tags: ['健身', '热身'],
        ),
        _createTemplate(
          id: 'fitness_record_weight',
          title: '记录体重体脂',
          description: '测量并记录体重和体脂率',
          category: TemplateCategory.fitness,
          priority: TaskPriority.low,
          estimatedMinutes: 5,
          icon: Icons.monitor_weight,
          tags: ['健身', '记录'],
        ),
        _createTemplate(
          id: 'fitness_protein',
          title: '补充蛋白质',
          description: '训练后30分钟内补充蛋白质',
          category: TemplateCategory.fitness,
          priority: TaskPriority.medium,
          estimatedMinutes: 5,
          icon: Icons.local_drink,
          tags: ['健身', '营养'],
        ),
        _createTemplate(
          id: 'fitness_hydration',
          title: '喝水2L',
          description: '全天喝水至少2升，保持水分',
          category: TemplateCategory.fitness,
          priority: TaskPriority.medium,
          estimatedMinutes: 0,
          icon: Icons.water_drop,
          tags: ['健身', '健康', '喝水'],
        ),
      ];

  /// 工作学习模板
  static List<TaskTemplate> get workTemplates => [
        _createTemplate(
          id: 'work_meeting',
          title: '团队会议',
          description: '参加团队例会或项目讨论',
          category: TemplateCategory.work,
          priority: TaskPriority.high,
          estimatedMinutes: 60,
          icon: Icons.groups,
          tags: ['工作', '会议'],
        ),
        _createTemplate(
          id: 'work_email',
          title: '处理邮件',
          description: '查看并回复工作邮件',
          category: TemplateCategory.work,
          priority: TaskPriority.medium,
          estimatedMinutes: 30,
          icon: Icons.email,
          tags: ['工作', '邮件'],
        ),
        _createTemplate(
          id: 'work_code_review',
          title: '代码审查',
          description: '审查团队成员的代码提交',
          category: TemplateCategory.work,
          priority: TaskPriority.high,
          estimatedMinutes: 45,
          icon: Icons.code,
          tags: ['工作', '编程'],
        ),
        _createTemplate(
          id: 'work_study',
          title: '学习新技术',
          description: '学习新的技术或工具',
          category: TemplateCategory.work,
          priority: TaskPriority.medium,
          estimatedMinutes: 60,
          icon: Icons.school,
          tags: ['学习', '技术'],
        ),
        _createTemplate(
          id: 'work_plan',
          title: '制定工作计划',
          description: '规划本周或本日工作任务',
          category: TemplateCategory.work,
          priority: TaskPriority.high,
          estimatedMinutes: 20,
          icon: Icons.calendar_today,
          tags: ['工作', '计划'],
        ),
      ];

  /// 日常生活模板
  static List<TaskTemplate> get lifeTemplates => [
        _createTemplate(
          id: 'life_shopping',
          title: '买菜购物',
          description: '去超市或市场采购食材',
          category: TemplateCategory.life,
          priority: TaskPriority.medium,
          estimatedMinutes: 45,
          icon: Icons.shopping_cart,
          tags: ['生活', '购物'],
        ),
        _createTemplate(
          id: 'life_cooking',
          title: '做饭',
          description: '准备一日三餐',
          category: TemplateCategory.life,
          priority: TaskPriority.high,
          estimatedMinutes: 60,
          icon: Icons.restaurant,
          tags: ['生活', '做饭'],
        ),
        _createTemplate(
          id: 'life_cleaning',
          title: '打扫卫生',
          description: '清洁房间和整理物品',
          category: TemplateCategory.life,
          priority: TaskPriority.medium,
          estimatedMinutes: 60,
          icon: Icons.cleaning_services,
          tags: ['生活', '清洁'],
        ),
        _createTemplate(
          id: 'life_laundry',
          title: '洗衣服',
          description: '清洗和晾晒衣物',
          category: TemplateCategory.life,
          priority: TaskPriority.medium,
          estimatedMinutes: 30,
          icon: Icons.local_laundry_service,
          tags: ['生活', '洗衣'],
        ),
        _createTemplate(
          id: 'life_reading',
          title: '阅读',
          description: '阅读书籍或文章',
          category: TemplateCategory.life,
          priority: TaskPriority.low,
          estimatedMinutes: 30,
          icon: Icons.book,
          tags: ['生活', '阅读'],
        ),
      ];

  /// 健康医疗模板
  static List<TaskTemplate> get healthTemplates => [
        _createTemplate(
          id: 'health_checkup',
          title: '体检',
          description: '进行定期健康检查',
          category: TemplateCategory.health,
          priority: TaskPriority.high,
          estimatedMinutes: 120,
          icon: Icons.medical_services,
          tags: ['健康', '体检'],
        ),
        _createTemplate(
          id: 'health_medicine',
          title: '按时吃药',
          description: '按医嘱服用药物',
          category: TemplateCategory.health,
          priority: TaskPriority.high,
          estimatedMinutes: 5,
          icon: Icons.medication,
          tags: ['健康', '用药'],
        ),
        _createTemplate(
          id: 'health_sleep',
          title: '早睡',
          description: '23:00前上床睡觉',
          category: TemplateCategory.health,
          priority: TaskPriority.high,
          estimatedMinutes: 0,
          icon: Icons.bedtime,
          tags: ['健康', '睡眠'],
        ),
        _createTemplate(
          id: 'health_eye',
          title: '眼保健操',
          description: '做眼保健操或眼部放松',
          category: TemplateCategory.health,
          priority: TaskPriority.medium,
          estimatedMinutes: 10,
          icon: Icons.visibility,
          tags: ['健康', '护眼'],
        ),
      ];

  /// 社交娱乐模板
  static List<TaskTemplate> get socialTemplates => [
        _createTemplate(
          id: 'social_friend',
          title: '联系朋友',
          description: '给朋友打电话或发消息',
          category: TemplateCategory.social,
          priority: TaskPriority.low,
          estimatedMinutes: 20,
          icon: Icons.phone,
          tags: ['社交', '朋友'],
        ),
        _createTemplate(
          id: 'social_family',
          title: '陪伴家人',
          description: '与家人共度时光',
          category: TemplateCategory.social,
          priority: TaskPriority.high,
          estimatedMinutes: 60,
          icon: Icons.family_restroom,
          tags: ['社交', '家人'],
        ),
        _createTemplate(
          id: 'social_movie',
          title: '看电影',
          description: '观看电影或电视剧',
          category: TemplateCategory.social,
          priority: TaskPriority.low,
          estimatedMinutes: 120,
          icon: Icons.movie,
          tags: ['娱乐', '电影'],
        ),
        _createTemplate(
          id: 'social_game',
          title: '玩游戏',
          description: '休闲游戏娱乐',
          category: TemplateCategory.social,
          priority: TaskPriority.low,
          estimatedMinutes: 60,
          icon: Icons.sports_esports,
          tags: ['娱乐', '游戏'],
        ),
      ];

  /// 财务管理模板
  static List<TaskTemplate> get financeTemplates => [
        _createTemplate(
          id: 'finance_record',
          title: '记账',
          description: '记录当日收支情况',
          category: TemplateCategory.finance,
          priority: TaskPriority.medium,
          estimatedMinutes: 10,
          icon: Icons.account_balance_wallet,
          tags: ['财务', '记账'],
        ),
        _createTemplate(
          id: 'finance_bill',
          title: '缴费',
          description: '缴纳水电煤气等账单',
          category: TemplateCategory.finance,
          priority: TaskPriority.high,
          estimatedMinutes: 15,
          icon: Icons.payment,
          tags: ['财务', '缴费'],
        ),
        _createTemplate(
          id: 'finance_review',
          title: '财务复盘',
          description: '回顾本月收支情况',
          category: TemplateCategory.finance,
          priority: TaskPriority.medium,
          estimatedMinutes: 30,
          icon: Icons.pie_chart,
          tags: ['财务', '复盘'],
        ),
      ];

  /// 创建模板的辅助方法
  static TaskTemplate _createTemplate({
    required String id,
    required String title,
    required TemplateCategory category, String? description,
    TaskPriority priority = TaskPriority.medium,
    int? estimatedMinutes,
    IconData? icon,
    List<String> tags = const [],
  }) {
    return TaskTemplate(
      id: id,
      title: title,
      description: description,
      category: category,
      priority: priority,
      estimatedMinutes: estimatedMinutes,
      tags: tags,
      iconCodePoint: icon?.codePoint,
      isBuiltIn: true,
      usageCount: 0,
      createdAt: DateTime.now(),
    );
  }
}
